# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f77038d7fb8e68c87390ef164da8ad36055c9fd3ca19d62cc5dc07a60259a2f796552b3b04a6fdf45776511693675cbbd1774e2c044ea4e88e91d67d9aff05b

test:
  secret_key_base: 51845cac1b86132caa5d2a4c22a9a0a94ef44fa335e4bb69d613db1937f2781fd2fab09b0594e7e151d9dda4554307e86713ffaec4ea943be5b1f13c4682cab6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
